### ISSUE TITLE
explore gem-based Jekyll themes

### ISSUE THREAD

**Issue by elotroalex** [elotroalex/ed#39]

**Comment by elotroalex** [comment]
https://jekyllrb.com/docs/themes/

**Comment by barmintor** [comment]
This would vastly simplify the installation process (no git requirement and possibility of a command line tool, `$ jekyll-ed new` or similar) and also make it possible to have the content be the traceable source history of an edition (if using git, you could fork a text rather than Ed). It would also give you an upgrade path for jekyll and Ed. Is there a downside?

**Comment by elotroalex** [comment]
If there is a downside, surely "it should be fixable." I'm getting to this
soon.

On Wed, Feb 8, 2017 at 11:13 AM, Benjamin Armintor <notifications@github.com

**Comment by elotroalex** [comment]
created first gem based theme and pushed to rubygems as "ed."

**Comment by elotroalex** [comment]
closing here, and opening more specific tasks
